wsl-segup

diff --git a/bin/wsl-setup b/bin/wsl-setup
--- a/bin/wsl-setup
+++ b/bin/wsl-setup
@@ -44,7 +44,50 @@ set_dirs() {
     git clone https://github.com/carcheky/ccktools.git
   fi
 }
+update_repo() {
+  if [[ -d /c/wsl/user/ccktools ]]; then
+    cd /c/wsl/user/ccktools/
+    if git pull
+      then
+        echo "ccktools updated"
+      else
+        echo "ccktools update failed"
+    fi
+  fi
+}
 
+create_links() {
+  if [[ -d /c/wsl/user/ccktools ]]; then
+      cd /c/wsl/user/ccktools/
+
+    if ! grep -q "bash -c /c/wsl/user/ccktools/bin/wsl-update" ~/.bashrc ; then
+      echo "bash -c /c/wsl/user/ccktools/bin/wsl-update" >> ~/.bashrc
+    fi
+
+    if ! grep -q "source /c/wsl/user/ccktools/.ccktools" ~/.bashrc ; then
+      echo "source /c/wsl/user/ccktools/.ccktools" >> ~/.bashrc
+    fi
+    
+    if ! grep -q "source /c/wsl/user/ccktools/.ccktools_aliases" ~/.bashrc ; then
+      echo "source /c/wsl/user/ccktools/.ccktools_aliases" >> ~/.bashrc
+    fi
+
+    if [[ -f ~/.zshrc  ]]; then
+      if ! grep -q "source /c/wsl/user/ccktools/.ccktools" ~/.zshrc ; then
+        echo "source /c/wsl/user/ccktools/.ccktools" >> ~/.zshrc
+      fi
+      
+      if ! grep -q "source /c/wsl/user/ccktools/.ccktools_aliases" ~/.zshrc ; then
+        echo "source /c/wsl/user/ccktools/.ccktools_aliases" >> ~/.zshrc
+      fi
+    fi
+
+    sudo apt install dos2unix -y
+    
+    find ~/bin/ -type f -exec chmod +x {} \;
+    find ~/bin/ -type f -exec dos2unix {} \;
+  fi
+}
 
 ################
 # MAIN PROGRAM #
